### ISSUE TITLE
リンクを別タブで表示する方法について

### ISSUE THREAD

**Issue by OshitaTatsuya** [ws-4020/mobile-app-handson#18]
環境構築ガイドとReact Nativeの公式ドキュメントを同時に参照しながら進めたい為、リンクを別タブで表示する方法を調査する。

**Comment by tani-takanori** [comment]
hugo使うならlayoutsで
https://agrimprasad.com/post/hugo-goldmark-markdown/

v2.docusaurus.io
ならいい感じにできるでしょ

**Comment by tani-takanori** [comment]
docusaurusで対応できるのでclose
